version: '3'
services:
  localstack:
    image: localstack/localstack
    ports:
      - '4566-4599:4566-4599'  # Expose LocalStack's standard ports
    environment:
      - SERVICES=s3,sqs,sns,lambda,dynamodb # Adjust services as needed
      - DATA_DIR=/tmp/localstack
      - DEBUG=1
      - PERSISTENCE=1
    volumes:
      - ${LOCALSTACK_VOLUME_DIR:-/tmp/localstack}:/var/lib/localstack
      - /var/run/docker.sock:/var/run/docker.sock  # For Docker-in-Docker features
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4566/_localstack/health"]
      interval: 5s
      timeout: 5s
      retries: 5
  ums:
    build:
      context:
        .
    container_name: ums
    environment:
      AWS_REGION: ${AWS_REGION:-ap-south-1}
      AWS_ACCESS_KEY: ${AWC_ACCESS_KEY:-test}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY:-test}
      AWS_ENDPOINT_URL: ${AWS_ENDPOINT_URL:-http://localhost:4566}
    ports:
      - "9999:9999"
