debug: true

server:
  port: 9999
  ssl:
    enabled: false

logging:
  level:
    com.example.ums: trace
    org.springframework: trace

spring:
  application:
    name: ums
  # colored console log messsages
  output:
    ansi:
      enabled: always
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${cognito.issuer-uri}
          jwks-uri: ${cognito.jwks-uri}

cognito:
  userpool-id: ap-south-1_h1l0zAs0z
  client-id: "2r7cqks9bo59crtb9qm1mn3b99"
  client-secret: "14sc5ram1jv85kfqdmua6urh719re5opd50j9pudf0rclpncfneo"
  client-redirect-uri: "https://127.0.0.1:9999/oauth2/callback"

